name:                expression-problem
version:             0.1.0.0
github:              "dabliuw22/expression-problem"
license:             BSD3
author:              "Will Leyton"
maintainer:          "wleylop22@gmail.com"
copyright:           "2020 Will Leyton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dabliuw22/expression-problem#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  expression-problem-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - expression-problem

tests:
  expression-problem-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - expression-problem
